powertrain:
  bias: [0.25,0.25,0.25,0.25] #OPTIMIZE 
  engine:
    idle_rpm : 710 #Measured from the real data 
    minimum_rpm: 600 #rpm                      # Minimum in all tests 
    maximum_rpm: 7324 #rpm                     # Maximum in all tests 
    w_table: [600.0,1821,5837,6835,7324]       # [rpm]  # automobile-catalog.com
    torque_max: [290,750,750,640,516]          # [Nm]  # Torque extrapolated from 1000 to 600 rpm
    inertia: 1.2        #OPTIMIZE                  # engine_inertia [Kgm^2] 0.8
 
  torque_converter:
    speed_ratio: [0,0.23,0.92, 1]  #Manually adapted from the real data 
    ratio: [2.5, 1.3, 0.95, 0.95]  #Manually adapted from the real data 
    factor: [0.04582197, 0.02773522, 0.01706852, 0.01279646, 0.01051292, 0.00982103, 0.00913212, 0.00769946, 0.00682872, 0.00627394, 0.00306653]
    CONVERTER_SYNC_TIME: 10 #Manually adapted on the real data 
    lock_up_ratio: 0.92 #Manually adapted on the real data 

  gearbox:
    MIN_GEAR_CHANGE_INTERVAL: 200 #Stimated from Double lane change_Dry_Automatic_Light_70_Repetition 1
                #N, 1st, 2nd, 3rd,   4th,   5th,   6th, 7th,   8th
    gear_ratio: [0, 5.0, 3.2, 2.143, 1.720, 1.313, 1.0, 0.823, 0.64]  #BMW Technical Data
                    #N,  1st,  2nd,  3rd,  4th,  5th,  6th,  7th,  8th
    gear_max_rpm: [[0.0, 6500, 6200, 6200, 6200, 6200, 6200, 6200, 6200], #0% [0.0, 1750, 2350, 2000, 2000, 2000, 2000, 2000, 2000], #0%
                   [0.0, 1750, 2350, 2000, 2000, 2000, 2000, 2000, 2000], #10%
                   [0.0, 1750, 2350, 2000, 2000, 2000, 2000, 2000, 2000], #20%
                   [0.0, 1750, 2350, 2000, 2000, 2000, 2000, 2000, 2000], #30%
                   [0.0, 2250, 2350, 2000, 2000, 2000, 2000, 2000, 2000], #40%
                   [0.0, 2250, 2550, 2750, 2750, 2750, 2750, 2750, 2750], #50%
                   [0.0, 2250, 2850, 3650, 3650, 3650, 3650, 3650, 3650], #60%
                   [0.0, 2500, 3050, 3650, 3650, 3650, 3650, 3650, 3650], #70%
                   [0.0, 2850, 4300, 4300, 4300, 4300, 4300, 4300, 4300], #80%
                   [0.0, 4700, 4700, 4700, 4700, 4700, 4700, 4700, 4700], #90%
                   [0.0, 6500, 6200, 6200, 6200, 6200, 6200, 6200, 6200]] #100%  # Calculated

    gear_min_rpm: [[0.0, 750, 800, 1300, 1400, 1200, 1000, 1000, 1000],   #0%
                   [0.0, 1000, 1500, 1750, 2000, 2375, 2600, 2600, 2600], #10%
                   [0.0, 1000, 1500, 1750, 2000, 2375, 2600, 2600, 2600], #20%
                   [0.0, 1000, 1500, 1750, 2000, 2375, 2600, 2600, 2600], #30%
                   [0.0, 1000, 1500, 1750, 2000, 2375, 2600, 2600, 2600], #40%
                   [0.0, 1000, 1500, 1750, 2000, 2375, 2600, 2600, 2600], #50%
                   [0.0, 1000, 1500, 1750, 2000, 2375, 2600, 2600, 2600], #60%
                   [0.0, 1000, 1500, 1750, 2000, 2375, 2600, 2600, 2600], #70%
                   [0.0, 1000, 1500, 1750, 2000, 2375, 2600, 2600, 2600], #80%
                   [0.0, 1000, 1500, 1750, 2000, 2375, 2600, 2600, 2600], #90%
                   [0.0, 1000, 1500, 1750, 2000, 2375, 2600, 2600, 2600]] #100%  # Calculated

    efficiency: 0.95 #0.95 # Efficiency of the whole powertrain system   #OPTIMIZE
    inertia: 0.1                             # Gear Box Inertia [Kgm^2]  #OPTIMIZE 0.05
  
  differential:  
    ratio: 3.154                            # Differential ratio   #BMW Technical Data
    driveshaft_inertia: 0.9 #7.8596          # drive shaft Inertia [Kgm^2]  #OPTIMIZE

brake:
  max_braking_torque: 17500.                 # [N/m]
  brake_bias: [0.30,0.20,0.30,0.20]          # [%]

steering:
  maximum_steering_angle: 20.               # maximum steering angle [rad] # Need to be checked! 25.1
  ratio: 14.3                               #BMW Technical Data

tire:
  relaxation: 0.1
  inertia: [1.5, 2.0, 1.5, 2.0]                     # Wheel Inertia on each wheel [Kgm^2] #OPTIMIZE
  rolling_resistance_coefficient: 0.08
  longitudinal:
    peak_friction : 1.1
    shape_factor : 1.3
    slip_stiffness : 22
  lateral:
    peak_friction : 1.1
    shape_factor : 1.3
    cornering_coefficient : 30.
  dynamic_radius: [0.35025, # FL - 275/35 ZR20
                   0.35375, # RL - 285/35 ZR20
                   0.35025, # FR - 275/35 ZR20
                   0.35375] # RR - 285/35 ZR20     # Tire Radius [m] 

aerodynamics:
  air_drag_coefficient: 0.33                  # BMW Technical Data
  front_area: 2.25                            # BMW Technical Data
  air_density: 1.2                            # Air Density 

suspension:
  roll_bar_stiffness: 2000 #5546.58                  #OPTIMIZE
  pitch_centre_height: 0.05                      #OPTIMIZE distance from the CG to the pitch center 
  roll_centre_height: 0.05                     #OPTIMIZE distance from the CG to the roll center 
  unsprung_mass: [100.0, 99.0, 100.0, 99.0]
  

  spring_rate: [18795.0, 14184.0, 18795.0, 14184.0]
  #damping_rate: [5026.0, 5249.0, 5026.0, 5249.0] 
  damping_rate: [1200.0, 1200.0, 1200.0, 1200.0]
      
body:
  lf: 1.331                                  # x-distance from Vehicle CoG to the front axle [m]            # Measured
  lr: 1.496                                  # x-distance from Vehicle Cog to the rear axle [m]             # Measured
  wl: 0.804                                  # y-distance from Vehicle CoG to the left chassis point [m]    # Measured
  wr: 0.826                                  # y-distance from Vehicle CoG to the right chassis point  [m]  # Measured
  sz: -0.078                                 # z-distance from Vehicle CoG to the chassis point [m]         # Measured NEED TO BE CHECKED - POSSIBLE OPTIMIZATION
  mass: 2074.4                               # Vehicle Mass                                                 # Measured

  # Body inertias
  i_x_s: 800.0                              # moment of inertia for sprung mass in roll [kg m^2] 818.05                 #OPTIMIZE
  i_y_s: 2638.0                                # moment of inertia for sprung mass in pitch [kg m^2] 2277.                 #OPTIMIZE
  i_z: 4983.0                                  # moment of inertia for sprung mass in yaw [kg m^2] 1921.3                  #OPTIMIZE
  